### ISSUE TITLE
ImportError with recent beets version

### ISSUE THREAD

**Issue by andrewjw** [adamjakab/BeetsPluginBpmAnalyser#21]
```
** error loading plugin bpmanalyser:
Traceback (most recent call last):
  File "/home/andrew/.local/lib/python3.10/site-packages/beets/plugins.py", line 269, in load_plugins
    namespace = __import__(modname, None, None)
  File "/usr/local/lib/python3.10/dist-packages/beetsplug/bpmanalyser/__init__.py", line 9, in <module>
    from beets.util import cpu_count
ImportError: cannot import name 'cpu_count' from 'beets.util' (/home/andrew/.local/lib/python3.10/site-packages/beets/util/__init__.py)
```

### Setup

* OS: Linux
* Python version: 3.10.12
* Beets version: Latest git (as of 21 September 2024)
* Turning off other plugins made problem go away (yes/no): no

**Comment by andrewjw** [comment]
This was removed in this commit - https://github.com/beetbox/beets/commit/19470f3d767ea8b1435f81748821068af2c79661

Looks like the fix is replace it with `os.cpu_count()`

**Comment by andrewjw** [comment]
I think I was running an old version of this plug in (the problem was fixed in https://github.com/adamjakab/BeetsPluginBpmAnalyser/commit/15cfd1e9c57546157c21184c197f67f6a7ec332e). Sorry for the noise!
